// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuneVault.Infrastructure.Persistence;

#nullable disable

namespace TuneVault.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TuneVault.Domain.Entities.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("AlbumId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            ArtistName = "Sơn Tùng M-TP",
                            CoverImageUrl = "/image/noinaycoanh.png",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(6911), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Album V-Pop Hay Nhất",
                            OwnerUserId = "U001",
                            Title = "V-Pop Hits",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(6912), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            AlbumId = 2,
                            ArtistName = "Đen",
                            CoverImageUrl = "/image/mangtienvechome.jpg",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(8470), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Album nhạc Rap ý nghĩa",
                            OwnerUserId = "U001",
                            Title = "Rap Việt",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(8471), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "U001",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(7091), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "TuneVault Admin",
                            Email = "admin@tunevault.com",
                            IsActive = true,
                            PasswordHash = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(7096), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "U002",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8784), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Nguyễn Yến Vy",
                            Email = "vy@tunevault.com",
                            IsActive = true,
                            PasswordHash = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8786), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "U003",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8900), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Trần Minh Khang",
                            Email = "khang@tunevault.com",
                            IsActive = true,
                            PasswordHash = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8900), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "U004",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8906), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Lê Hoài Linh",
                            Email = "linh@tunevault.com",
                            IsActive = true,
                            PasswordHash = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8907), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "U005",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8911), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Phạm Quốc An",
                            Email = "an@tunevault.com",
                            IsActive = true,
                            PasswordHash = "A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 912, DateTimeKind.Unspecified).AddTicks(8912), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Follow", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FollowerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowingUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FollowId");

                    b.HasIndex("FollowingUserId");

                    b.HasIndex("FollowerUserId", "FollowingUserId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.MediaItem", b =>
                {
                    b.Property<int>("MediaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaItemId"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("AlbumTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Audio");

                    b.Property<string>("MimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PlayCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Public");

                    b.HasKey("MediaItemId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Title");

                    b.HasIndex("Visibility");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            MediaItemId = 1,
                            AlbumId = 1,
                            AlbumTitle = "V-Pop Hits",
                            ArtistName = "Sơn Tùng M-TP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(9997), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "TuneVault Admin",
                            OwnerUserId = "U001",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/noinaycoanh.png",
                            Title = "Nơi Này Có Anh",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 913, DateTimeKind.Unspecified).AddTicks(9998), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 2,
                            ArtistName = "Hoàng Thùy Linh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2542), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "TuneVault Admin",
                            OwnerUserId = "U001",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/seetinh.jpg",
                            Title = "See Tình",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2543), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 3,
                            AlbumId = 2,
                            AlbumTitle = "Rap Việt",
                            ArtistName = "Đen",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2551), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "TuneVault Admin",
                            OwnerUserId = "U001",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/mangtienvechome.jpg",
                            Title = "Mang Tiền Về Cho Mẹ",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2551), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 8,
                            ArtistName = "Vũ.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2556), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "TuneVault Admin",
                            OwnerUserId = "U001",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/lalung.jpg",
                            Title = "Lạ Lùng",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2557), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 10,
                            ArtistName = "ERIK",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2560), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "TuneVault Admin",
                            OwnerUserId = "U001",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/sautatca.jpg",
                            Title = "Sau Tất Cả",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2560), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 15,
                            ArtistName = "MONSTAR, GREY D",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2563), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Nguyễn Yến Vy",
                            OwnerUserId = "U002",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/cohenvoithanhxuan.jpg",
                            Title = "Có Hẹn Với Thanh Xuân",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2564), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 16,
                            ArtistName = "Sơn Tùng MTP",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2566), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Nguyễn Yến Vy",
                            OwnerUserId = "U002",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/comemyway.jpg",
                            Title = "Come My Way",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2567), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 17,
                            ArtistName = "Min Quỳnh Anh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2570), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Trần Minh Khang",
                            OwnerUserId = "U003",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/emthuacota.jpg",
                            Title = "Em Thua Cô Ta",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2571), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 18,
                            ArtistName = "HIEUTHUHAI",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2573), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Trần Minh Khang",
                            OwnerUserId = "U003",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/khongthesay.jpg",
                            Title = "Không Thể Say",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2574), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 19,
                            ArtistName = "MONO",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2576), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Lê Hoài Linh",
                            OwnerUserId = "U004",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/waitingforyou.jpg",
                            Title = "Waiting For You",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2577), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 20,
                            ArtistName = "Phan Mạnh Quỳnh",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2580), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Lê Hoài Linh",
                            OwnerUserId = "U004",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/cochangtrai.jpg",
                            Title = "Có Chàng Trai Viết Lên Cây",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2580), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            MediaItemId = 21,
                            ArtistName = "Nguyễn Thành Đạt",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2583), new TimeSpan(0, 0, 0, 0, 0)),
                            DurationSeconds = 0,
                            FilePath = "temp-upload-test.mp3",
                            FileSizeBytes = 0L,
                            IsProcessed = true,
                            MediaType = "Audio",
                            OwnerDisplayName = "Phạm Quốc An",
                            OwnerUserId = "U005",
                            PlayCount = 0,
                            ThumbnailUrl = "/image/thiephongsaiten.jpg",
                            Title = "Thiệp Hồng Sai Tên",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(2584), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.MediaShare", b =>
                {
                    b.Property<int>("MediaShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaShareId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SenderUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MediaShareId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("MediaShares");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("ActorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("MediaShareId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationId");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.PlayHistory", b =>
                {
                    b.Property<int>("PlayHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayHistoryId"));

                    b.Property<int>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayHistoryId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayHistories");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCollaborative")
                        .HasColumnType("bit");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Private");

                    b.HasKey("PlaylistId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(3744), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCollaborative = false,
                            OwnerUserId = "U001",
                            Title = "V-Pop Hits Collection",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(3745), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        },
                        new
                        {
                            PlaylistId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(4720), new TimeSpan(0, 0, 0, 0, 0)),
                            IsCollaborative = false,
                            OwnerUserId = "U002",
                            Title = "Chill Vibes",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(4721), new TimeSpan(0, 0, 0, 0, 0)),
                            Visibility = "Public"
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.PlaylistTrack", b =>
                {
                    b.Property<int>("PlaylistTrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaylistTrackId"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MediaItemId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.HasKey("PlaylistTrackId");

                    b.HasIndex("MediaItemId");

                    b.HasIndex("PlaylistId", "MediaItemId")
                        .IsUnique();

                    b.ToTable("PlaylistTracks");

                    b.HasData(
                        new
                        {
                            PlaylistTrackId = 1,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(5485), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaItemId = 1,
                            PlaylistId = 1
                        },
                        new
                        {
                            PlaylistTrackId = 2,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(6328), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaItemId = 8,
                            PlaylistId = 1
                        },
                        new
                        {
                            PlaylistTrackId = 3,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(6331), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaItemId = 10,
                            PlaylistId = 1
                        },
                        new
                        {
                            PlaylistTrackId = 4,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(6333), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaItemId = 15,
                            PlaylistId = 2
                        },
                        new
                        {
                            PlaylistTrackId = 5,
                            AddedAt = new DateTimeOffset(new DateTime(2026, 6, 24, 20, 34, 47, 914, DateTimeKind.Unspecified).AddTicks(6334), new TimeSpan(0, 0, 0, 0, 0)),
                            MediaItemId = 16,
                            PlaylistId = 2
                        });
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Album", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.MediaItem", "MediaItem")
                        .WithMany("Favorites")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Follow", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.MediaItem", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Owner")
                        .WithMany("MediaItems")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.MediaShare", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.MediaItem", "MediaItem")
                        .WithMany()
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TuneVault.Domain.Entities.Playlist", "Playlist")
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Playlist");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Notification", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.AppUser", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.PlayHistory", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.MediaItem", "MediaItem")
                        .WithMany("PlayHistories")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Entities.AppUser", "User")
                        .WithMany("PlayHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Playlist", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.AppUser", "Owner")
                        .WithMany("Playlists")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("TuneVault.Domain.Entities.MediaItem", "MediaItem")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("MediaItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TuneVault.Domain.Entities.Playlist", "Playlist")
                        .WithMany("Tracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaItem");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("MediaItems");

                    b.Navigation("Notifications");

                    b.Navigation("PlayHistories");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.MediaItem", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("PlayHistories");

                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("TuneVault.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
